from .employees.employee_list import employee_list
from .home import home
from .auth.logout import logout_user
from .training_programs.training_list import training_list
from .training_programs.training_form import training_form
from .departments.department_list import department_list
from .departments.department_details import department_details
from .departments.department_form import department_form
from .computers import computer_list
from .computers import computer_form
